### ISSUE TITLE
Heatmap labels can be too small to read

### ISSUE THREAD

**Issue by waxlamp** [girder/viime#598]
via @joannawolthuis:
> I noticed that the heatmap does show compound names, but they are tiny(illegible) if you have many. Would you consider making the compound names (and sample names) visible on mouse hover in a tooltip?

(split from #597)

**Comment by waxlamp** [comment]
@joannawolthuis, if you try Viime again (at https://viime.org/) you should see that this issue has been resolved.

Please re-open this thread if you have further comments or concerns.

**Comment by joannawolthuis** [comment]
Hi there! Thanks for taking a look :) I went to check, but now I see no labels at all - which doesn't have to be a problem, but then labels on hover or something like that would be useful, otherwise you can't really interpret the heatmap that well (except on a group basis if you were to add a bar with for example treatment membership)..

**Comment by waxlamp** [comment]
Sorry that my original response didn't give the full story.

When I try this out using the `Cancer chemo serum (MS)` example dataset, the labels are indeed not visible when first loading the heatmap. However, when I hover over a cell, I do see the cell information (including labels) in a tooltip. Are you not seeing those?

And there is now a new layout option for the heatmap labeled `Full`, which renders the heatmap large enough to show all labels in a 12pt font. This view may require you to scroll to see the whole thing.

Please let me know if these options are ok. Thanks!

**Comment by joannawolthuis** [comment]
Hi @waxlamp ! Thanks for taking a look :) Hover still doesn't work for me, see pic, I'm using google chrome if that matters.
![image](https://user-images.githubusercontent.com/16805477/92456135-d48a3c00-f1c2-11ea-8bc8-6f5ba1beeb5d.png)
Full view is great, love the addition!

**Comment by waxlamp** [comment]
Hi @joannawolthuis. Sorry you are still having some trouble. I note that on occasion, if you quickly try to get a tooltip to appear soon after the heatmap loads, it won't work--but then waiting a moment and trying again will show the tooltips. I cannot reproduce the situation where tooltips simply don't show up at all.

Could you let me know what version of Chrome you're using?

And if it's not too much trouble, I wonder if could open the developer console (e.g., with the F12 key), then try to hover over a heatmap cell and let me know if anything shows up in the console?

Thanks!

**Comment by joannawolthuis** [comment]
Hi, thanks for your fast response! I double checked, if I wait a little while it indeed works :) Would be ideal if it was immediate but this is ok, you can close! If you still want me to check in dev. console, let me know.
